baseURL = 'https://monblog.fr/'
languageCode = 'fr-fr'
title = 'Mon Blog'
theme = "LoveIt"
[params.home]
  # bloc "profil" en page d’accueil
  [params.home.profile]
    enable = true
    subtitle = "Ici je raconte des trucs utiles (promis)"
    # (optionnel)
    avatarURL = "/images/uploads/avatar.png"
    social = true   # affiche les icônes sociales si configurées

[params.header.title]
      # title name
      name = "Mon Blog"