# netlify.toml
[build]
  # Si TON SITE est à la racine du repo :
  base = ""
  command = "hugo"
  publish = "public"

  # ⬇️ Si TON SITE est dans un sous-dossier (ex: "site"):
  # base = "site"
  # command = "hugo"
  # publish = "public"

[build.environment]
  HUGO_VERSION = "0.128.2"
  HUGO_EXTENDED = "true"   # LoveIt a besoin de l’extended (SCSS)
  TZ = "Europe/Paris"
